#### DataTypes for tensors

In [2]:
'''
floating -- for most deep learning tasks --> float32,float64,float16
integers -- for categorical data and indices --> int32,int64,int8
boolean --  for mask or logical operation 
Complex Number -- advanced computations  --> complex64,complex128

memory consumption: float16 << float32 << float64
computation: lower precision will be faster on gpu
numerical precision: float64 is more precise than float32

'''

'\nfloating -- for most deep learning tasks --> float32,float64,float16\nintegers -- for categorical data and indices --> int32,int64,int8\nboolean --  for mask or logical operation \nComplex Number -- advanced computations  --> complex64,complex128\n\nmemory consumption: float16 << float32 << float64\ncomputation: lower precision will be faster on gpu\nnumerical precision: float64 is more precise than float32\n\n'

In [3]:
import torch

In [ ]:
default_tensor = torch.tensor([1.5,2.5,3.5])
print(default_tensor.dtype)

torch.float32


In [5]:
float_tensor = torch.tensor([1.5,2.5,3.5],dtype=torch.float64)
print(float_tensor.dtype)

torch.float64


In [7]:
int_tensor = torch.tensor([1.5,2.5,3.5],dtype=torch.int32)
print(int_tensor.dtype)
print(int_tensor)

torch.int32
tensor([1, 2, 3], dtype=torch.int32)


In [8]:
int_tensor = torch.tensor([1,2,3])
print(int_tensor.dtype)

torch.int64


In [10]:
bool_tensor = torch.tensor([True,False,False,True])
print(bool_tensor)
print(bool_tensor.dtype)


tensor([ True, False, False,  True])
torch.bool


#### type conversion

In [14]:
float_tensor = torch.tensor([1.5,2.4,6.5])
print(float_tensor)
print(float_tensor.dtype)


int_tensor  = float_tensor.to(torch.int64)
print(int_tensor)
print(int_tensor.dtype)

tensor([1.5000, 2.4000, 6.5000])
torch.float32
tensor([1, 2, 6])
torch.int64


In [15]:
int_tensor = torch.tensor([1,0,4,-5])
bool_tensor = int_tensor.to(torch.bool)
print(bool_tensor)
print(bool_tensor.dtype)

tensor([ True, False,  True,  True])
torch.bool


#### Impact of data type on memory

In [18]:
float32_tensor = torch.ones(1000,dtype=torch.float32)
float64_tensor = torch.ones(1000,dtype=torch.float64)


# element_size() --> gives the size of one element in bytes
# nelement() ---> returns total number of elements
print(float32_tensor.element_size())
print(float32_tensor.nelement())
print(f"Memory used by float32 tensor:{float32_tensor.element_size() * float32_tensor.nelement()} bytes")
print(f"Memory used by float64 tensor:{float64_tensor.element_size() * float64_tensor.nelement()} bytes")


4
1000
Memory used by float32 tensor:4000 bytes
Memory used by float64 tensor:8000 bytes


In [ ]:
# float32 --> default for most NN models
# float64 --> high precision computation
# int32 --> general purpose integer
# int64 --> tensor indices 
# int8,int16 --> reduce memory usage
# float16 --> half precision of default floating datatype,reduce memory usage