In [1]:
import torch

In [5]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])


print(f"Tensor1 Dimension is {tensor_1.ndim} and the Size is {tensor_1.size()}")

Tensor1 Dimension is 1 and the Size is torch.Size([3])


In [9]:
stacked_tensor_dim_0 = torch.stack((tensor_1,tensor_2),dim=0)
print("Shape:",stacked_tensor_dim_0.shape)
print(stacked_tensor_dim_0)

print("-"*20)
stacked_tensor_dim_1 = torch.stack((tensor_1,tensor_2),dim=1)
print("Shape:",stacked_tensor_dim_1.shape)
print(stacked_tensor_dim_1)

Shape: torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
--------------------
Shape: torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [11]:
tensor3 = torch.tensor([7,8,9])
stacked_tensor_dim_0_new = torch.stack((tensor_1,tensor_2,tensor3),dim=0)
print("Shape:",stacked_tensor_dim_0_new.shape)
print(stacked_tensor_dim_0_new)
print("-"*20)
stacked_tensor_dim_1_new = torch.stack((tensor_1,tensor_2,tensor3),dim=1)
print("Shape:",stacked_tensor_dim_1_new.shape)
print(stacked_tensor_dim_1_new)

Shape: torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
--------------------
Shape: torch.Size([3, 3])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


##### stacking 2D tensor

In [ ]:
tensor1 = torch.tensor([[1,2],
                        [3,4]])
tensor2 = torch.tensor([[5,6],
                        [7,8]])
print("Dimension:",tensor2.ndim)

stacked_tensor_2d = torch.stack((tensor1,tensor2),dim=0)
print("Dimension:",stacked_tensor_2d.ndim)
print("Shape:",stacked_tensor_2d.shape)
print(stacked_tensor_2d)

Dimension: 2
Dimension: 3
Shape: torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


###### [1,2] dim-->0 = []. dim-->1 = values
###### [[1,2]]. dim-->0 = [1,2],dim-->1 = 1,2, dim -->2 = 1, 2 [seprate 1 and 2]

In [15]:
stacked_tensor_2d = torch.stack((tensor1,tensor2),dim=1)
print("Dimension:",stacked_tensor_2d.ndim)
print("Shape:",stacked_tensor_2d.shape)
print(stacked_tensor_2d)

Dimension: 3
Shape: torch.Size([2, 2, 2])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [16]:
stacked_tensor_2d = torch.stack((tensor1,tensor2),dim=2)
print("Dimension:",stacked_tensor_2d.ndim)
print("Shape:",stacked_tensor_2d.shape)
print(stacked_tensor_2d)

Dimension: 3
Shape: torch.Size([2, 2, 2])
tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


In [17]:
stacked_tensor_2d = torch.stack((tensor1,tensor2),dim=3)
print("Dimension:",stacked_tensor_2d.ndim)
print("Shape:",stacked_tensor_2d.shape)
print(stacked_tensor_2d)

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

###### Concatenation operation
concate will not create extra dim

In [21]:
concatenated_tensor = torch.cat((tensor1,tensor2),dim=0)
print("Shape:",concatenated_tensor.shape)
print(concatenated_tensor)
print("Dimension:",concatenated_tensor.ndim)


Shape: torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Dimension: 2


In [22]:
concatenated_tensor = torch.cat((tensor1,tensor2),dim=1)
print("Shape:",concatenated_tensor.shape)
print(concatenated_tensor)
print("Dimension:",concatenated_tensor.ndim)

Shape: torch.Size([2, 4])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Dimension: 2
