In [1]:
import torch

In [2]:
tensor = torch.arange(12)

##### view only works with contiguous data
##### reshape works with both
###### if reshape gets non-contiguous data it creates copy of contiguous data and uses that copy

In [3]:
reshaped_view_tensor = tensor.view(2,6)
reshaped_tensor = tensor.reshape(2,6)


print(reshaped_view_tensor)
print(reshaped_tensor)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [4]:
tensor.is_contiguous()

True

In [6]:
inferred_shape = tensor.view(3,-1)
print(inferred_shape)
print(inferred_shape.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [7]:
tensor_3d = torch.arange(24).reshape(2,3,4)
print(tensor_3d)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


###### cnn requires input as a 1d so we can use -1 to convert any D into 1d

In [8]:
flattned = tensor_3d.view(-1)
print(flattned)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [9]:
flattned.is_contiguous()

True

In [10]:
tensor_3d = torch.arange(24).reshape(12,2)
transposed_tensor = tensor_3d.t()


In [11]:
transposed_tensor.is_contiguous()

False

In [12]:
error = transposed_tensor.view(6,4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [13]:
reshaped_tensor = transposed_tensor.reshape(6,4)
print(reshaped_tensor)
print(reshaped_tensor.shape)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])


In [14]:
contiguous = transposed_tensor.contiguous()
error = contiguous.view(6,4)
print(error)
print(error.shape)


tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])
