In [6]:
# Accessing elements in a tensor
'''
tesnor[row,column]
'''
import torch

# Indexing

In [12]:
tensor = torch.tensor([[10,20,30],
                       [40,50,60],
                       [70,80,90]])
print(tensor.ndim)
print(tensor.shape)

2
torch.Size([3, 3])


In [7]:
print("Element at (0,1):",tensor[0,1])

Element at (0,1): tensor(20)


In [10]:
# Access first row
tensor[0]

tensor([10, 20, 30])

In [13]:
# Access first column
tensor[:,0]

tensor([10, 40, 70])

# Slicing

In [16]:
print("First two rows:\n",tensor[:2,:])

First two rows:
 tensor([[10, 20, 30],
        [40, 50, 60]])


In [17]:
print("First two columns:\n",tensor[:,:2])

First two columns:
 tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [21]:
# Middle element (row:1,columns:1&2 only)
print(tensor[1,1:3])

tensor([50, 60])


In [22]:
# Fancy indexing
# (0,1) --> 20
# (2,2) --> 90

selected_elements = tensor[[0,2],[1,2]]
print(selected_elements)

tensor([20, 90])


In [ ]:
# boolean indexing

mask = tensor > 50
print(mask)

print(tensor[mask])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [25]:
# Modifying values via indexing
print(tensor) 

tensor[0,1] = 25

print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [26]:
tensor[:,0] = torch.tensor([100,200,300])
print(tensor)

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [29]:
indices = torch.tensor([0,2])
selected_rows = torch.index_select(tensor,dim=1,index=indices) # 0 -> rows, 1 -> columns

print(selected_rows)

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [31]:
# Using tensor with steps

print(tensor[:,::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [34]:
# print(tensor[::-1]) # wont work this in pytorch
torch.flip(tensor,dims=(0,))

tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])