### Tensor Manipulation
###### - reshaping
###### - slicing
###### - joining or splitting
###### - transposing and permuting dimension

In [20]:
import torch

In [21]:
# Reshaping tensors
original_tensor = torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print("Dimension:",original_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
Dimension: 1


In [22]:
reshaped_tensor = original_tensor.reshape(2,6)
print(reshaped_tensor)
print("Dimension:",reshaped_tensor.ndim)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Dimension: 2


In [23]:
reshaped_tensor = original_tensor.reshape(3,4)
print(reshaped_tensor)
print("Dimension:",reshaped_tensor.ndim)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Dimension: 2


In [26]:
# View
print(original_tensor.is_contiguous())
flatten_tensor = original_tensor.view(-1)
print(flatten_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


##### Slicing
###### Extract specific portions of tensors

In [28]:
tensor_a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print("Dimension:",tensor_a.ndim)



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Dimension: 2


In [29]:
tensor_a[0]

tensor([1, 2, 3])

In [30]:
tensor_a[:,0]

tensor([1, 4, 7])

In [31]:
print(tensor_a.shape)

torch.Size([3, 3])


In [35]:
sub_tensor = tensor_a[1:,1:]
print(sub_tensor.shape)
print(sub_tensor)

torch.Size([2, 2])
tensor([[5, 6],
        [8, 9]])


##### Joining tensors

###### torch.cat() --> it merges tensors along an existing dimension.

In [46]:
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

print(tensor1)
print(tensor2)


print("="*25)

concatenated_tensor_rows = torch.cat((tensor1,tensor2),dim=0)
concatenated_tensor_columns = torch.cat((tensor1,tensor2),dim=1)


print(concatenated_tensor_rows)
print(concatenated_tensor_columns)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


###### stack -> creates a new dimension, increases the tensor's rank


In [ ]:
print(tensor1.shape)
print(tensor2.shape)


print("="*25)


stack_tensor_rows = torch.stack((tensor1,tensor2),dim=0)
stack_tensor_columns = torch.stack((tensor1,tensor2),dim=1)

print(stack_tensor_rows.shape)
print(stack_tensor_columns.shape)


print(stack_tensor_rows)
print(stack_tensor_columns)




torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


##### Spliting tensors
###### torch.chunk() --> divides your tensor into equal-sized chunks
###### torch.split() --> allows uneven spliting based on size

In [53]:
# torch.chunk()

original_tensor = torch.arange(12)

chunks = torch.chunk(original_tensor,chunks=4,dim=0)  # max 4 possible

print(chunks)
print(type(chunks))

for chunk in chunks:
    print(chunk)




(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
<class 'tuple'>
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [55]:
# torch.split()

original_tensor = torch.arange(12)

splits = torch.split(original_tensor,split_size_or_sections=7,dim=0)  # max 4 possible

print(splits)
print(type(splits))

for split in splits:
    print(split)


(tensor([0, 1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11]))
<class 'tuple'>
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([ 7,  8,  9, 10, 11])


#### Transposing and Permuting

###### - transpose() ---> swaps two dim. mxn->nxm
###### - permute() ----> rearranges all dim in the specified order

In [59]:
# Transpose-
original_tensor = torch.arange(32).reshape(16,2)

transposed_tensor = original_tensor.transpose(0,1)
print(original_tensor.shape)
print(transposed_tensor.shape)

print("-"*20)
print(original_tensor)
print(transposed_tensor)

torch.Size([16, 2])
torch.Size([2, 16])
--------------------
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]])


In [66]:
# Permuting
original_tensor = torch.arange(32).reshape(2,4,4)
print(original_tensor)
print("Shape:",original_tensor.shape)
print("-"*30)
permuted_tensor = original_tensor.permute(2,0,1)
print(permuted_tensor)
print("Shape:",permuted_tensor.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]]])
Shape: torch.Size([2, 4, 4])
------------------------------
tensor([[[ 0,  4,  8, 12],
         [16, 20, 24, 28]],

        [[ 1,  5,  9, 13],
         [17, 21, 25, 29]],

        [[ 2,  6, 10, 14],
         [18, 22, 26, 30]],

        [[ 3,  7, 11, 15],
         [19, 23, 27, 31]]])
Shape: torch.Size([4, 2, 4])


##### Cloning and detaching

In [69]:
# Python way
import copy

a = [1,2,3,4,5]
b = copy.deepcopy(a)

print(id(a))
print(id(b))



140561725986880
140561725988224


In [70]:
tensor = torch.ones(3,3,requires_grad=True) # part of computation graph

cloned_tensor = tensor.clone()  # for cloning [part of computation graph]

detached_tensor = tensor.detach()  # this code will detach the tensor from the computation graph [not a part of comp. graph]
# but storage will be same as the original ones


