In [1]:
import torch

In [2]:
matrix = torch.tensor([[1.,2.,3.],
              [4.,5.,6.],
              [7.,8.,9.]])

print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [7]:
print(matrix.sum())
print(matrix.min())
print(matrix.max())
print(matrix.mean())
print(matrix.median())

tensor(45.)
tensor(1.)
tensor(9.)
tensor(5.)
tensor(5.)


###### dim=0 ---> rows [actual columns]
###### dim=1 ---> columns [actual rows]


In [13]:
print(matrix.min(dim=0))
print("-"*10)
print(matrix.max(dim=0))
print("-"*10)
print(matrix.sum(dim=1))


torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
----------
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
----------
tensor([ 6., 15., 24.])


##### Cumulative Sum

In [17]:
cumulative_sum = matrix.cumsum(dim=1)
print(cumulative_sum)

tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.],
        [ 7., 15., 24.]])


In [18]:
cumulative_sum = matrix.cumsum(dim=0)
print(cumulative_sum)

tensor([[ 1.,  2.,  3.],
        [ 5.,  7.,  9.],
        [12., 15., 18.]])


##### Advance Aggregation

In [20]:
masked_matrix_sum = matrix[matrix>8].sum()
print(masked_matrix_sum)

tensor(9.)


In [28]:
matrix = torch.tensor([[0.,0.,0.],
              [4.,5.,6.],
              [7.,8.,9.]])

non_zero = matrix.nonzero()
print(non_zero)
print(non_zero.shape)
print(non_zero.size(0))

tensor([[1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])
torch.Size([6, 2])
6


##### Normalized Matrix

In [29]:
max_v = matrix.max()
min_v = matrix.min()

normalized_matrix = (matrix - min_v) / (max_v - min_v)

print(normalized_matrix)


tensor([[0.0000, 0.0000, 0.0000],
        [0.4444, 0.5556, 0.6667],
        [0.7778, 0.8889, 1.0000]])
